version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5123}:${PORT:-5123}"
    volumes:
      - ./contents:/app/contents
    environment:
      - PORT=${PORT:-5123}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NODE_ENV=production
      - WHISPER_CPU_ONLY=1
    restart: unless-stopped

volumes:
  contents:
    driver: local
