version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "${PORT:-5123}:${PORT:-5123}"
    volumes:
      - ./contents:/app/contents
    environment:
      - PORT=${PORT:-5123}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NODE_ENV=production
    depends_on:
      - whisper
    restart: unless-stopped
    networks:
      - shorts-network

  whisper:
    build:
      context: .
      dockerfile: Dockerfile.whisper
    volumes:
      - ./contents:/app/contents
    restart: unless-stopped
    networks:
      - shorts-network
    environment:
      - WHISPER_CPU_ONLY=1

# Create a named volume for persistent storage
volumes:
  contents:
    driver: local

networks:
  shorts-network:
    driver: bridge
